# Generated by Django 6.0.4 on 2026-05-17 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0007_alter_cart_id_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Men',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasm1', models.ImageField(upload_to='media')),
                ('narxi1', models.IntegerField()),
                ('skidkasi1', models.IntegerField()),
                ('tavsifi1', models.CharField(max_length=100)),
                ('category1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Base.category')),
            ],
        ),
    ]
