# Generated by Django 6.0.6 on 2026-06-22 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='narxi',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='rasm',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='item',
            name='skidkasi',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='tavsifi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
